### ISSUE TITLE
Problem with php PEAR

### ISSUE THREAD

**Issue by karmicdude** [debops/phpipam#4]
I use Docker image based on alpine, php7.1-fpm with required extension, php7-pear is also installed:

```bash
$ docker-compose exec ipam sh

/ # pear version
PEAR Version: 1.10.4
PHP Version: 7.1.5
Zend Engine Version: 3.1.0
Running on: Linux ipam 4.11.8-1-zen #1 ZEN SMP PREEMPT Thu Jun 29 21:25:23 UTC 2017 x86_64

/ # php-fpm7 -m
[PHP Modules]
cgi-fcgi
Core
date
filter
gd
gettext
gmp
hash
json
ldap
libxml
mbstring
mcrypt
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
readline
Reflection
session
SimpleXML
sockets
SPL
standard
xml

/ # php-fpm7 -i | grep pear
Configure Command =>  ./configure  '--build=x86_64-alpine-linux-musl' ...
 '--with-pear=/usr/share/php7' '--with-config-file-path=/etc/php7'  ...

/ # pear config-get php_dir
/usr/share/php7

/ # php -c /etc/php7/php.ini -r 'echo get_include_path()."\n";'
.:/usr/share/php7
```

But phpipam return 
```
The following required PHP extensions are missing:
php PEAR support
Please recompile PHP to include missing extensions and restart Apache.
```
I edited `functions/checks/check_php_build.php` and tried to change directive with pear check like that:
```
# check for PEAR functions
if ((@include_once '/usr/share/php7') != true) {
        $missingExt[] = "php PEAR support";
}
```
and it works, but I'd like to find what causes this problem to automate the process of update the container without kludges like an applying `sed` to edit a repo file.

**Comment by drybjed** [comment]
I'm sorry, this is an unmaintained, old fork of the phpIPAM code from back when it was published in a SVN repository on SourceForge. You could try checking if the current version of [phpIPAM](https://github.com/phpipam/phpipam/) works for you.

**Comment by karmicdude** [comment]
sry, not there wrote
